/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2024-04-17 10:44:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.SignInVO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.SignInVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

if(request.getAttribute("signUp_ok") != null){
	String signUp_ok = (String)request.getAttribute("signUp_ok");

      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\talert(\"회원가입 성공. 로그인해주세요.\");\r\n");
      out.write("\t\t</script>\r\n");

}

if(session.getAttribute("user") != null){
	SignInVO user = (SignInVO) session.getAttribute("user");
	System.out.println("유저가 널이 아닌 곳에 왔습니다");
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\talert(\"로그인 성공.\");\r\n");
      out.write("\t\tdocument.body.html('");
      out.print(user.getId() );
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print(user.getPassword() );
      out.write("');\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}

if(request.getAttribute("loginError") != null){
	
      out.write(" \r\n");
      out.write("\t<script>\r\n");
      out.write("\t\talert(\"아이디 또는 비밀번호가 잘못되었습니다.\");\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Say That</title>\r\n");
      out.write("<!--  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js\"></script>\r\n");
      out.write(" -->\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("section{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tborder: 1px solid black;\r\n");
      out.write("\tborder-radius: 30px;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("  \ttop: 50%;\r\n");
      out.write("  \tleft: 50%;\r\n");
      out.write("  \ttransform: translate(-50%,20%);\r\n");
      out.write("}\r\n");
      out.write("svg{\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("\tdisplay: flex;\r\n");
      out.write("\talign-items: center;\r\n");
      out.write("\tmargin: 15%;\r\n");
      out.write("}\r\n");
      out.write(".side{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("ul{\r\n");
      out.write("\t/* list-style: none;*/\r\n");
      out.write("}\r\n");
      out.write("li{\r\n");
      out.write("\tpadding: 5%;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("p{\r\n");
      out.write("\tfont-family: sans-serif;\r\n");
      out.write("\tfont-size: 1.0rem;\r\n");
      out.write("\tmargin-top: 5%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<section>\r\n");
      out.write("<svg version=\"1.1\" id=\"Layer_1\" xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" x=\"0px\" y=\"0px\"\r\n");
      out.write("\t viewBox=\"0 0 563.7 231.3\" style=\"enable-background:new 0 0 563.7 231.3;\" xml:space=\"preserve\">\r\n");
      out.write("<path d=\"M62.4,62.7H39V31.5c0-4.4-3.4-7.8-7.8-7.8s-7.8,3.4-7.8,7.8v21.1c0,17.9,12,25.7,22.6,40c7,9.6,15.3,21.8,16.1,44.2\r\n");
      out.write("\tc0.3,6,0.3,9.4,0.3,11.7c0,32-20,39-31.2,39s-31.2-7-31.2-39V116h23.4v40.3c0,4.4,3.4,7.8,7.8,7.8s7.8-3.4,7.8-7.8v-19.5\r\n");
      out.write("\tc0-19.5-5.2-26.8-17.4-42.4C11.7,82.5,0,70.5,0,52.6v-13C0,7.1,20.3,0.3,31.2,0.3c11.2,0,31.2,7,31.2,39V62.7z\"/>\r\n");
      out.write("<path d=\"M133.6,82.5v102.4h-19.8l-1.3-15.1c-2.6,9.4-8.1,17.7-19.5,17.7c-10.1,0-19.8-6.5-19.8-32.8v-10.9\r\n");
      out.write("\tc0-26.3,10.1-32.8,21.1-32.8c8.8,0,14,4.4,16.9,10.4v-39c0-4.4-3.4-7.8-7.8-7.8s-7.8,3.4-7.8,7.8v15.6H73.2V82.5\r\n");
      out.write("\tc0-23.1,19-30.2,30.2-30.2S133.6,59.4,133.6,82.5z M111.2,157.4v-22.9c0-1.8-3.4-5.2-7.8-5.2s-7.8,3.4-7.8,10.4v15.1\r\n");
      out.write("\tc0,7,3.4,10.4,7.8,10.4S111.2,161.8,111.2,157.4z\"/>\r\n");
      out.write("<path d=\"M142.5,54.9h22.9l9.6,95.7l8.1-95.7h22.4L179.6,232h-20.8l8.1-47.1L142.5,54.9z\"/>\r\n");
      out.write("<path d=\"M341.1,26.3h-23.4v158.6h-23.4V26.3h-23.4V2.9h70.2V26.3z\"/>\r\n");
      out.write("<path d=\"M354.2,184.9V2.9h22.4v63.4c3.1-8.1,9.1-14,20.3-14c10.1,0,17.7,7.3,17.7,30.4v102.2h-22.4V82.8c0-3.1-3.4-6.5-7.8-6.5\r\n");
      out.write("\ts-7.8,3.4-7.8,7.8v100.9H354.2z\"/>\r\n");
      out.write("<path d=\"M491.6,82.5v102.4h-19.8l-1.3-15.1c-2.6,9.4-8.1,17.7-19.5,17.7c-10.1,0-19.8-6.5-19.8-32.8v-10.9\r\n");
      out.write("\tc0-26.3,10.1-32.8,21.1-32.8c8.8,0,14,4.4,16.9,10.4v-39c0-4.4-3.4-7.8-7.8-7.8s-7.8,3.4-7.8,7.8v15.6h-22.4V82.5\r\n");
      out.write("\tc0-23.1,19-30.2,30.2-30.2C472.6,52.3,491.6,59.4,491.6,82.5z M469.3,157.4v-22.9c0-1.8-3.4-5.2-7.8-5.2s-7.8,3.4-7.8,10.4v15.1\r\n");
      out.write("\tc0,7,3.4,10.4,7.8,10.4S469.3,161.8,469.3,157.4z\"/>\r\n");
      out.write("<polygon points=\"505,55 502.8,55 500,55 500,76 504.1,76 506,76 563,76 563,55 \"/>\r\n");
      out.write("<polygon points=\"508.4,3.5 529.2,185.6 550.3,185.7 529.5,3.6 \"/>\r\n");
      out.write("</svg>\r\n");
      out.write("<!-- <h2 class=\"sayThat\">Say That</h2>  -->\r\n");
      out.write("<div class=\"side\">\r\n");
      out.write("\t<p>하지 못한 말을 해야한다! 말로 쓰는 나만의 일기장. <br></p>\r\n");
      out.write("<ul>\r\n");
      out.write("  \t<li>\r\n");
      out.write("    \t<a href=\"/signUp\">회원가입 페이지</a>\r\n");
      out.write("  \t</li>\r\n");
      out.write("  \t<li>\r\n");
      out.write("  \t  <a href=\"/signIn\">로그인</a>\r\n");
      out.write("  \t</li>\r\n");
      out.write("  \t<li>\r\n");
      out.write("  \t  <a href=\"/recording\">일기 쓰기</a>\r\n");
      out.write("  \t</li>\r\n");
      out.write("</ul>\r\n");
      out.write("</div>\r\n");
      out.write("</section>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
