/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2024-04-17 11:55:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vo.SignInVO;

public final class recording_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("vo.SignInVO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

SignInVO vo = null;
if(session.getAttribute("user") == null){
	
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t");
 System.out.println("잘못된 곳으로 왔습니다.");
      out.write("\r\n");
      out.write("\t\talert(\"로그인 후 다시 사용해주세요.\");\r\n");
      out.write("\t\tlocation.href=\"/\";\r\n");
      out.write("\t</script>\r\n");
      out.write("\t");

}else {
	vo = (SignInVO)session.getAttribute("user");
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Say That</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<h2>Say That</h2>\r\n");
      out.write("<p>하지 못한 말을 해야한다! Say That 녹음 사이트입니다. <br></p>\r\n");
      out.write("<button id=\"recordBtn\">녹음 시작</button> <button id=\"resetBtn\">녹음초기화</button>\r\n");
      out.write("<br><br>\r\n");
      out.write("<audio controls>녹음된 소리를 재생할 audio 엘리먼트</audio>\r\n");
      out.write("<div id=\"sound-clips\"></div>\r\n");
      out.write("<script>\r\n");
      out.write("  //엘리먼트 취득\r\n");
      out.write("  const $audioEl = document.querySelector(\"audio\");\r\n");
      out.write("  const $recordBtn = document.querySelector(\"#recordBtn\");\r\n");
      out.write("  const $soundClips = document.querySelector(\"#sound-clips\");\r\n");
      out.write("\r\n");
      out.write("  // 녹음중 상태 변수\r\n");
      out.write("  let isRecording = false;\r\n");
      out.write("\r\n");
      out.write("  // MediaRecorder 변수 생성\r\n");
      out.write("  let mediaRecorder = null;\r\n");
      out.write("\r\n");
      out.write("  // 녹음 데이터 저장 배열\r\n");
      out.write("  let audioArray = [];\r\n");
      out.write("\r\n");
      out.write("  $recordBtn.onclick = async function () {\r\n");
      out.write("      if (!isRecording) {\r\n");
      out.write("          // 녹음 시작\r\n");
      out.write("          if (!mediaRecorder) {\r\n");
      out.write("              // 최초 녹음 시작\r\n");
      out.write("              const mediaStream = await navigator.mediaDevices.getUserMedia({audio: true});\r\n");
      out.write("              mediaRecorder = new MediaRecorder(mediaStream);\r\n");
      out.write("\r\n");
      out.write("              mediaRecorder.ondataavailable = (event) => {\r\n");
      out.write("                  audioArray.push(event.data);\r\n");
      out.write("              };\r\n");
      out.write("\r\n");
      out.write("              mediaRecorder.onstop = () => {\r\n");
      out.write("                  // 녹음 중지 시 녹음 데이터를 하나의 오디오 파일로 합침\r\n");
      out.write("                  const blob = new Blob(audioArray, {\"type\": \"audio/ogg codecs=opus\"});\r\n");
      out.write("                  const blobURL = window.URL.createObjectURL(blob);\r\n");
      out.write("                  $audioEl.src = blobURL;\r\n");
      out.write("\r\n");
      out.write("                  // 녹음완료 버튼 생성\r\n");
      out.write("                  const endButton = document.createElement('button');\r\n");
      out.write("                  endButton.textContent = '녹음완료';\r\n");
      out.write("                  endButton.onclick = function() {\r\n");
      out.write("                      // uploadAudio(blob);\r\n");
      out.write("                      \r\n");
      out.write("                \t\t// 기존에 입력 요소가 이미 추가되어 있다면 제거\r\n");
      out.write("                \t    const existingInputs = document.querySelectorAll('.additional-input');\r\n");
      out.write("                \t    existingInputs.forEach(input => {\r\n");
      out.write("                \t        input.remove();\r\n");
      out.write("                \t    });\r\n");
      out.write("\r\n");
      out.write("                \t    // 게시글 제목 입력 요소 생성 및 추가\r\n");
      out.write("                \t    const titleInput = document.createElement('input');\r\n");
      out.write("                \t    titleInput.setAttribute('type', 'text');\r\n");
      out.write("                \t    titleInput.setAttribute('placeholder', '게시글 제목을 입력하세요');\r\n");
      out.write("                \t    titleInput.classList.add('additional-input');\r\n");
      out.write("                \t    $soundClips.appendChild(titleInput);\r\n");
      out.write("\r\n");
      out.write("                \t    // 사진 파일1 입력 요소 생성 및 추가\r\n");
      out.write("                \t    const photoInput1 = document.createElement('input');\r\n");
      out.write("                \t    photoInput1.setAttribute('type', 'file');\r\n");
      out.write("                \t    photoInput1.setAttribute('accept', 'image/jpeg');\r\n");
      out.write("                \t    photoInput1.classList.add('additional-input');\r\n");
      out.write("                \t    $soundClips.appendChild(photoInput1);\r\n");
      out.write("\r\n");
      out.write("                \t    // 사진 파일2 입력 요소 생성 및 추가\r\n");
      out.write("                \t    const photoInput2 = document.createElement('input');\r\n");
      out.write("                \t    photoInput2.setAttribute('type', 'file');\r\n");
      out.write("                \t    photoInput2.setAttribute('accept', 'image/jpeg');\r\n");
      out.write("                \t    photoInput2.classList.add('additional-input');\r\n");
      out.write("                \t    $soundClips.appendChild(photoInput2);\r\n");
      out.write("                \t    \r\n");
      out.write("                \t    const uploadButton = document.createElement('button');\r\n");
      out.write("                \t    uploadButton.textContent = '등록하기';\r\n");
      out.write("                \t    uploadButton.onclick = function() {\r\n");
      out.write("                            uploadAudio(blob);\r\n");
      out.write("                        };\r\n");
      out.write("                        $soundClips.appendChild(uploadButton);\r\n");
      out.write("                  };\r\n");
      out.write("                  $soundClips.appendChild(endButton);\r\n");
      out.write("              };\r\n");
      out.write("          }\r\n");
      out.write("          \r\n");
      out.write("          mediaRecorder.start();\r\n");
      out.write("          isRecording = true;\r\n");
      out.write("          $recordBtn.textContent = \"녹음 중지\";\r\n");
      out.write("      } else {\r\n");
      out.write("          // 녹음 중지\r\n");
      out.write("          mediaRecorder.stop();\r\n");
      out.write("          isRecording = false;\r\n");
      out.write("          $recordBtn.textContent = \"녹음 시작\";\r\n");
      out.write("      }\r\n");
      out.write("  };\r\n");
      out.write("\r\n");
      out.write("  // 녹음 초기화 버튼 추가\r\n");
      out.write("  const $resetBtn = document.querySelector(\"#resetBtn\");\r\n");
      out.write("\r\n");
      out.write("  $resetBtn.onclick = function() {\r\n");
      out.write("      // 녹음 초기화\r\n");
      out.write("      if (mediaRecorder && !isRecording) {\r\n");
      out.write("          audioArray = []; // 녹음 데이터 배열을 초기화\r\n");
      out.write("          $audioEl.src = \"\"; // 오디오 소스를 초기화\r\n");
      out.write("          mediaRecorder = null; // MediaRecorder 인스턴스를 초기화\r\n");
      out.write("          $recordBtn.textContent = \"녹음 시작\";\r\n");
      out.write("          // 기존에 생성된 녹음완료 버튼이 있다면 제거\r\n");
      out.write("          const endButton = $soundClips.querySelector('button');\r\n");
      out.write("          if (endButton) {\r\n");
      out.write("              $soundClips.removeChild(endButton);\r\n");
      out.write("          }\r\n");
      out.write("      }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  // 녹음 데이터를 서버로 업로드하는 함수\r\n");
      out.write("  function uploadAudio(blob) {\r\n");
      out.write("      const formData = new FormData();\r\n");
      out.write("      formData.append('audioFile', blob, 'recording.ogg');\r\n");
      out.write("      formData.append('userid', '");
      out.print(vo.getId() );
      out.write("');\r\n");
      out.write("      \r\n");
      out.write("   \t  // 게시글 제목 및 사진 파일 데이터 추가\r\n");
      out.write("      const titleInput = document.querySelector('input[type=\"text\"].additional-input');\r\n");
      out.write("      const photoInputs = document.querySelectorAll('input[type=\"file\"].additional-input');\r\n");
      out.write("\r\n");
      out.write("      // 게시글 제목을 formData에 추가\r\n");
      out.write("      if (titleInput) {\r\n");
      out.write("          formData.append('title', titleInput.value);\r\n");
      out.write("      }\r\n");
      out.write("\r\n");
      out.write("      var photoIndex = 1;\r\n");
      out.write("      console.log(photoIndex);\r\n");
      out.write("      // 사진 파일을 formData에 추가 (여러 파일을 가정)\r\n");
      out.write("      photoInputs.forEach((input, index) => {\r\n");
      out.write("          if (input.files[0]) { // 파일이 선택되었는지 확인\r\n");
      out.write("        \t  console.log(index, `photo");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${index + 1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`, input.files[0]);\r\n");
      out.write("          \t  var pname = 'photo' + (index + 1);\r\n");
      out.write("              formData.append(pname, input.files[0]);\r\n");
      out.write("              photoIndex = photoIndex + 1;\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("      photoIndex = 0;\r\n");
      out.write("      \r\n");
      out.write("      fetch('/recording', {\r\n");
      out.write("    \t    method: 'POST',\r\n");
      out.write("    \t    body: formData,\r\n");
      out.write("    \t}).then(response => {\r\n");
      out.write("    \t    if (response.ok) {\r\n");
      out.write("    \t        console.log('Upload success');\r\n");
      out.write("    \t        window.location.replace = '/postlist';\r\n");
      out.write("    \t    } else {\r\n");
      out.write("    \t        console.error('Upload failed');\r\n");
      out.write("    \t    }\r\n");
      out.write("    \t}).catch(error => {\r\n");
      out.write("    \t    console.error('Error:', error);\r\n");
      out.write("    \t});\r\n");
      out.write("\r\n");
      out.write("  }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
